# Generated by Django 5.2.14 on 2026-05-27 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=160)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('categoria', models.CharField(blank=True, max_length=120)),
                ('descripcion_corta', models.CharField(blank=True, max_length=240)),
                ('descripcion_larga', models.TextField(blank=True)),
                ('imagen_principal', models.FileField(blank=True, null=True, upload_to='productos/')),
                ('imagen_estatica', models.CharField(blank=True, help_text='Ruta static opcional. Ej: tienda/img/vinilo.svg', max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('destacado', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('tipo_calculo', models.CharField(choices=[('manual', 'Manual / requiere revisión'), ('area_m2', 'Área m²'), ('unidad', 'Por unidad')], default='area_m2', max_length=20)),
                ('precio_base_m2', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('precio_base_unidad', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('requiere_revision', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ProductoCampo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiqueta', models.CharField(max_length=160)),
                ('nombre_interno', models.SlugField(blank=True, max_length=120)),
                ('tipo', models.CharField(choices=[('texto', 'Texto corto'), ('texto_largo', 'Texto largo'), ('numero', 'Número decimal'), ('entero', 'Número entero'), ('select', 'Selección única'), ('multiselect', 'Selección múltiple'), ('checkbox', 'Checkbox / Sí-No'), ('archivo', 'Archivo'), ('imagen', 'Imagen de referencia'), ('color', 'Color'), ('fecha', 'Fecha')], default='texto', max_length=30)),
                ('obligatorio', models.BooleanField(default=False)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('ayuda', models.CharField(blank=True, max_length=255)),
                ('placeholder', models.CharField(blank=True, max_length=160)),
                ('activo', models.BooleanField(default=True)),
                ('afecta_area_ancho', models.BooleanField(default=False, help_text='Usar este campo como ancho en cm para calcular m²')),
                ('afecta_area_alto', models.BooleanField(default=False, help_text='Usar este campo como alto en cm para calcular m²')),
                ('es_cantidad', models.BooleanField(default=False, help_text='Usar este campo como cantidad')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campos', to='tienda.producto')),
            ],
            options={
                'verbose_name': 'Campo configurable',
                'verbose_name_plural': 'Campos configurables',
                'ordering': ['producto', 'orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CampoOpcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiqueta', models.CharField(max_length=160)),
                ('valor', models.SlugField(blank=True, max_length=120)),
                ('ajuste_tipo', models.CharField(choices=[('ninguno', 'No suma precio'), ('fijo', 'Valor fijo'), ('por_m2', 'Valor por m²'), ('por_unidad', 'Valor por unidad'), ('porcentaje', 'Porcentaje sobre base')], default='ninguno', max_length=20)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activa', models.BooleanField(default=True)),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='tienda.productocampo')),
            ],
            options={
                'verbose_name': 'Opción de campo',
                'verbose_name_plural': 'Opciones de campo',
                'ordering': ['campo', 'orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductoImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.FileField(upload_to='productos/galeria/')),
                ('titulo', models.CharField(blank=True, max_length=140)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activa', models.BooleanField(default=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='tienda.producto')),
            ],
            options={
                'verbose_name': 'Imagen de producto',
                'verbose_name_plural': 'Imágenes de producto',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nombre', models.CharField(max_length=160)),
                ('cliente_celular', models.CharField(max_length=40)),
                ('cliente_email', models.EmailField(blank=True, max_length=254)),
                ('estado', models.CharField(choices=[('nueva', 'Nueva'), ('revision', 'En revisión'), ('pendiente_info', 'Pendiente de información'), ('cotizada', 'Cotizada'), ('aprobada', 'Aprobada'), ('produccion', 'En producción'), ('lista', 'Lista para entrega'), ('entregada', 'Entregada'), ('cancelada', 'Cancelada')], default='nueva', max_length=30)),
                ('precio_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('precio_final', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('requiere_revision', models.BooleanField(default=False)),
                ('notas_internas', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to='tienda.producto')),
            ],
            options={
                'verbose_name': 'Solicitud',
                'verbose_name_plural': 'Solicitudes',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudRespuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiqueta', models.CharField(max_length=160)),
                ('tipo', models.CharField(max_length=30)),
                ('valor_texto', models.TextField(blank=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='solicitudes/archivos/')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('campo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tienda.productocampo')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='tienda.solicitud')),
            ],
            options={
                'verbose_name': 'Respuesta de solicitud',
                'verbose_name_plural': 'Respuestas de solicitud',
                'ordering': ['orden', 'id'],
            },
        ),
    ]
