# Generated by Django 5.2.14 on 2026-05-28 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_categoria_producto_categoria_fk'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='productocampo',
            constraint=models.UniqueConstraint(condition=models.Q(('afecta_area_ancho', True)), fields=('producto',), name='unico_campo_ancho_por_producto'),
        ),
        migrations.AddConstraint(
            model_name='productocampo',
            constraint=models.UniqueConstraint(condition=models.Q(('afecta_area_alto', True)), fields=('producto',), name='unico_campo_alto_por_producto'),
        ),
        migrations.AddConstraint(
            model_name='productocampo',
            constraint=models.UniqueConstraint(condition=models.Q(('es_cantidad', True)), fields=('producto',), name='unico_campo_cantidad_por_producto'),
        ),
    ]
