# Generated by Django 5.2.14 on 2026-05-29 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_productocampo_unico_campo_ancho_por_producto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampoMaestro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=160)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('tipo', models.CharField(choices=[('texto', 'Texto corto'), ('texto_largo', 'Texto largo'), ('numero', 'Número decimal'), ('entero', 'Número entero'), ('select', 'Selección única'), ('multiselect', 'Selección múltiple'), ('checkbox', 'Checkbox / Sí-No'), ('archivo', 'Archivo'), ('imagen', 'Imagen de referencia'), ('color', 'Color'), ('fecha', 'Fecha')], default='texto', max_length=30)),
                ('etiqueta_base', models.CharField(blank=True, max_length=160)),
                ('ayuda_base', models.CharField(blank=True, max_length=255)),
                ('placeholder_base', models.CharField(blank=True, max_length=160)),
                ('activo', models.BooleanField(default=True)),
                ('orden_base', models.PositiveIntegerField(default=0)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Campo maestro',
                'verbose_name_plural': 'Campos maestros',
                'ordering': ['orden_base', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='productocampo',
            name='campo_maestro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='producto_campos', to='tienda.campomaestro'),
        ),
        migrations.AddConstraint(
            model_name='productocampo',
            constraint=models.UniqueConstraint(condition=models.Q(('campo_maestro__isnull', False)), fields=('producto', 'campo_maestro'), name='unico_campo_maestro_por_producto'),
        ),
    ]
