# Generated by Django 5.2.14 on 2026-05-29 00:17

from django.db import migrations
from django.utils.text import slugify


def build_slug(campo):
    raw = campo.nombre_interno or campo.etiqueta or f"campo-{campo.pk}"
    base = slugify(raw) or f"campo-{campo.pk}"
    return f"{base[:100]}-{campo.tipo}"[:140]


def unique_slug(base, CampoMaestro):
    slug = base[:140] or "campo-maestro"
    if not CampoMaestro.objects.filter(slug=slug).exists():
        return slug

    root = slug[:130]
    index = 2
    while CampoMaestro.objects.filter(slug=f"{root}-{index}").exists():
        index += 1
    return f"{root}-{index}"


def create_master_from_field(campo, CampoMaestro, slug):
    return CampoMaestro.objects.create(
        nombre=campo.etiqueta,
        slug=slug,
        tipo=campo.tipo,
        etiqueta_base=campo.etiqueta,
        ayuda_base=campo.ayuda,
        placeholder_base=campo.placeholder,
        activo=True,
        orden_base=campo.orden,
    )


def forwards(apps, schema_editor):
    CampoMaestro = apps.get_model("tienda", "CampoMaestro")
    ProductoCampo = apps.get_model("tienda", "ProductoCampo")

    for campo in ProductoCampo.objects.filter(campo_maestro__isnull=True).order_by("id"):
        base_slug = build_slug(campo)
        maestro = CampoMaestro.objects.filter(slug=base_slug).first()
        if maestro and ProductoCampo.objects.filter(
            producto_id=campo.producto_id,
            campo_maestro_id=maestro.id,
        ).exclude(pk=campo.pk).exists():
            maestro = create_master_from_field(
                campo,
                CampoMaestro,
                unique_slug(f"{base_slug}-campo-{campo.pk}", CampoMaestro),
            )
        elif not maestro:
            maestro = create_master_from_field(campo, CampoMaestro, unique_slug(base_slug, CampoMaestro))

        ProductoCampo.objects.filter(pk=campo.pk).update(campo_maestro=maestro)


def backwards(apps, schema_editor):
    CampoMaestro = apps.get_model("tienda", "CampoMaestro")
    ProductoCampo = apps.get_model("tienda", "ProductoCampo")
    ProductoCampo.objects.update(campo_maestro=None)
    CampoMaestro.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_campomaestro_productocampo_campo_maestro_and_more'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
