# Generated by Django 5.2.14 on 2026-05-29 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_migrar_campos_a_maestros'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampoMaestroOpcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiqueta', models.CharField(max_length=160)),
                ('valor', models.SlugField(blank=True, max_length=120)),
                ('ajuste_tipo', models.CharField(choices=[('ninguno', 'No suma precio'), ('fijo', 'Valor fijo'), ('por_m2', 'Valor por m²'), ('por_unidad', 'Valor por unidad'), ('porcentaje', 'Porcentaje sobre base')], default='ninguno', max_length=20)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activa', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Opción maestra',
                'verbose_name_plural': 'Opciones maestras',
                'ordering': ['campo_maestro', 'orden', 'id'],
            },
        ),
        migrations.AddField(
            model_name='campomaestro',
            name='obligatorio_base',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='campoopcion',
            constraint=models.UniqueConstraint(fields=('campo', 'valor'), name='unica_opcion_por_campo_valor'),
        ),
        migrations.AddField(
            model_name='campomaestroopcion',
            name='campo_maestro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones_maestras', to='tienda.campomaestro'),
        ),
        migrations.AddConstraint(
            model_name='campomaestroopcion',
            constraint=models.UniqueConstraint(fields=('campo_maestro', 'valor'), name='unica_opcion_maestra_por_valor'),
        ),
    ]
