# Generated by Django 5.2.14 on 2026-05-29 00:52

from django.db import migrations
from django.db.models import Count
from django.utils.text import slugify


def option_value(opcion):
    return opcion.valor or slugify(opcion.etiqueta)[:120] or f"opcion-{opcion.pk}"


def forwards(apps, schema_editor):
    CampoMaestro = apps.get_model("tienda", "CampoMaestro")
    CampoMaestroOpcion = apps.get_model("tienda", "CampoMaestroOpcion")
    CampoOpcion = apps.get_model("tienda", "CampoOpcion")
    ProductoCampo = apps.get_model("tienda", "ProductoCampo")

    for campo in ProductoCampo.objects.filter(campo_maestro__isnull=False).order_by("id"):
        opciones = CampoOpcion.objects.filter(campo_id=campo.id).order_by("orden", "id")
        for opcion in opciones:
            valor = option_value(opcion)
            if CampoMaestroOpcion.objects.filter(campo_maestro_id=campo.campo_maestro_id, valor=valor).exists():
                continue
            CampoMaestroOpcion.objects.create(
                campo_maestro_id=campo.campo_maestro_id,
                etiqueta=opcion.etiqueta,
                valor=valor,
                ajuste_tipo=opcion.ajuste_tipo,
                precio=opcion.precio,
                orden=opcion.orden,
                activa=opcion.activa,
            )

    for maestro in CampoMaestro.objects.annotate(usos=Count("producto_campos")).filter(usos=0, activo=True):
        canonical = f"{(slugify(maestro.nombre) or 'campo').replace('-', '_')[:100]}-{maestro.tipo}"[:140]
        if canonical != maestro.slug and CampoMaestro.objects.filter(slug=canonical).exists():
            maestro.activo = False
            maestro.save(update_fields=["activo"])


def backwards(apps, schema_editor):
    CampoMaestroOpcion = apps.get_model("tienda", "CampoMaestroOpcion")
    CampoMaestroOpcion.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0006_campomaestroopcion_campomaestro_obligatorio_base_and_more'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
