# Generated by Django 5.2.14 on 2026-05-29 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0007_migrar_opciones_a_maestras'),
    ]

    operations = [
        migrations.AddField(
            model_name='campomaestro',
            name='valor_fijo_base',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='productocampo',
            name='valor_fijo',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='campomaestro',
            name='tipo',
            field=models.CharField(choices=[('texto', 'Texto corto'), ('texto_largo', 'Texto largo'), ('numero', 'Número decimal'), ('entero', 'Número entero'), ('select', 'Selección única'), ('multiselect', 'Selección múltiple'), ('checkbox', 'Checkbox / Sí-No'), ('archivo', 'Archivo'), ('imagen', 'Imagen de referencia'), ('color', 'Color'), ('fecha', 'Fecha'), ('valor_fijo', 'Valor fijo')], default='texto', max_length=30),
        ),
        migrations.AlterField(
            model_name='productocampo',
            name='tipo',
            field=models.CharField(choices=[('texto', 'Texto corto'), ('texto_largo', 'Texto largo'), ('numero', 'Número decimal'), ('entero', 'Número entero'), ('select', 'Selección única'), ('multiselect', 'Selección múltiple'), ('checkbox', 'Checkbox / Sí-No'), ('archivo', 'Archivo'), ('imagen', 'Imagen de referencia'), ('color', 'Color'), ('fecha', 'Fecha'), ('valor_fijo', 'Valor fijo')], default='texto', max_length=30),
        ),
    ]
