# Generated by Django 5.2.14 on 2026-05-30 04:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0008_campomaestro_valor_fijo_base_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='estado_produccion',
            field=models.CharField(choices=[('pendiente_asignar', 'Pendiente por asignar'), ('asignado', 'Asignado'), ('en_proceso', 'En proceso'), ('con_novedad', 'Con novedad'), ('terminado', 'Terminado'), ('calidad', 'En control de calidad'), ('listo_entrega', 'Listo para entrega'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente_asignar', max_length=30),
        ),
        migrations.CreateModel(
            name='EmpleadoPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, max_length=40)),
                ('cargo', models.CharField(blank=True, max_length=120)),
                ('area', models.CharField(choices=[('produccion', 'Produccion'), ('diseno', 'Diseno'), ('corte', 'Corte'), ('impresion', 'Impresion'), ('calidad', 'Calidad'), ('despacho', 'Despacho'), ('admin', 'Admin'), ('apoyo', 'Apoyo')], default='produccion', max_length=30)),
                ('activo', models.BooleanField(default=True)),
                ('puede_recibir_pedidos', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='empleado_perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'ordering': ['user__first_name', 'user__last_name', 'user__username'],
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=160)),
                ('mensaje', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('asignacion', 'Asignacion'), ('desasignacion', 'Desasignacion'), ('estado', 'Cambio de estado'), ('novedad', 'Novedad'), ('terminado', 'Terminado'), ('sistema', 'Sistema')], default='sistema', max_length=30)),
                ('leida', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('url_destino', models.CharField(blank=True, max_length=255)),
                ('solicitud', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='tienda.solicitud')),
                ('usuario_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificacion',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha_creacion', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudNovedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('comentario', 'Comentario'), ('cambio_estado', 'Cambio de estado'), ('asignacion', 'Asignacion'), ('desasignacion', 'Desasignacion'), ('evidencia', 'Evidencia'), ('sistema', 'Sistema'), ('alerta', 'Alerta')], default='comentario', max_length=30)),
                ('comentario', models.TextField()),
                ('estado_anterior', models.CharField(blank=True, max_length=30)),
                ('estado_nuevo', models.CharField(blank=True, max_length=30)),
                ('archivo_evidencia', models.FileField(blank=True, null=True, upload_to='solicitudes/evidencias/')),
                ('visible_para_admin', models.BooleanField(default=True)),
                ('visible_para_produccion', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='novedades', to='tienda.solicitud')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='novedades_solicitud', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Novedad de solicitud',
                'verbose_name_plural': 'Novedades de solicitud',
                'ordering': ['-fecha_creacion', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudAsignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('activa', models.BooleanField(default=True)),
                ('rol_en_trabajo', models.CharField(blank=True, max_length=120)),
                ('observacion', models.CharField(blank=True, max_length=255)),
                ('fecha_desasignacion', models.DateTimeField(blank=True, null=True)),
                ('asignado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_creadas', to=settings.AUTH_USER_MODEL)),
                ('desasignado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_desasignadas', to=settings.AUTH_USER_MODEL)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='tienda.empleadoperfil')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='tienda.solicitud')),
            ],
            options={
                'verbose_name': 'Asignacion de solicitud',
                'verbose_name_plural': 'Asignaciones de solicitud',
                'ordering': ['-activa', 'fecha_asignacion'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('activa', True)), fields=('solicitud', 'empleado'), name='unica_asignacion_activa_por_empleado')],
            },
        ),
    ]
