# Generated by Django 5.2.14 on 2026-05-30 05:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0009_solicitud_estado_produccion_empleadoperfil_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('asignacion', 'Asignacion'), ('desasignacion', 'Desasignacion'), ('estado', 'Cambio de estado'), ('novedad', 'Novedad'), ('terminado', 'Terminado'), ('tarea', 'Tarea'), ('proyecto', 'Proyecto'), ('sistema', 'Sistema')], default='sistema', max_length=30),
        ),
        migrations.AlterField(
            model_name='solicitudnovedad',
            name='tipo',
            field=models.CharField(choices=[('comentario', 'Comentario'), ('cambio_estado', 'Cambio de estado'), ('asignacion', 'Asignacion'), ('desasignacion', 'Desasignacion'), ('evidencia', 'Evidencia'), ('sistema', 'Sistema'), ('alerta', 'Alerta'), ('tarea_creada', 'Tarea creada'), ('tarea_asignada', 'Tarea asignada'), ('tarea_estado', 'Estado de tarea'), ('tarea_evidencia', 'Evidencia de tarea'), ('tarea_comentario', 'Comentario de tarea'), ('tarea_finalizada', 'Tarea finalizada')], default='comentario', max_length=30),
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=180)),
                ('cliente_nombre', models.CharField(blank=True, max_length=160)),
                ('cliente_contacto', models.CharField(blank=True, max_length=160)),
                ('cliente_telefono', models.CharField(blank=True, max_length=40)),
                ('cliente_email', models.EmailField(blank=True, max_length=254)),
                ('descripcion', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('pendiente', 'Pendiente'), ('en_planeacion', 'En planeacion'), ('en_produccion', 'En produccion'), ('pausado', 'Pausado'), ('terminado', 'Terminado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='borrador', max_length=30)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('normal', 'Normal'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='normal', max_length=20)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_compromiso', models.DateField(blank=True, null=True)),
                ('fecha_cierre', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos_creados', to=settings.AUTH_USER_MODEL)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proyectos_responsable', to='tienda.empleadoperfil')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['-fecha_creacion', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='notificacion',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones', to='tienda.proyecto'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes', to='tienda.proyecto'),
        ),
        migrations.CreateModel(
            name='SolicitudTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=180)),
                ('descripcion', models.TextField(blank=True)),
                ('area', models.CharField(choices=[('diseno', 'Diseno'), ('preprensa', 'Preprensa'), ('impresion', 'Impresion'), ('laminado', 'Laminado'), ('corte', 'Corte'), ('ensamble', 'Ensamble'), ('calidad', 'Calidad'), ('instalacion', 'Instalacion'), ('despacho', 'Despacho'), ('apoyo', 'Apoyo')], default='apoyo', max_length=30)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('asignada', 'Asignada'), ('en_proceso', 'En proceso'), ('bloqueada', 'Bloqueada'), ('terminada', 'Terminada'), ('aprobada', 'Aprobada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=30)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('normal', 'Normal'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='normal', max_length=20)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_limite', models.DateField(blank=True, null=True)),
                ('fecha_finalizacion', models.DateTimeField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('requiere_evidencia', models.BooleanField(default=False)),
                ('evidencia_archivo', models.FileField(blank=True, null=True, upload_to='solicitudes/tareas/evidencias/')),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('asignado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_asignadas', to=settings.AUTH_USER_MODEL)),
                ('finalizada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_finalizadas', to=settings.AUTH_USER_MODEL)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tareas', to='tienda.empleadoperfil')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='tienda.solicitud')),
            ],
            options={
                'verbose_name': 'Tarea de produccion',
                'verbose_name_plural': 'Tareas de produccion',
                'ordering': ['solicitud', 'orden', 'fecha_limite', 'id'],
            },
        ),
        migrations.AddField(
            model_name='notificacion',
            name='tarea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones', to='tienda.solicitudtarea'),
        ),
        migrations.AddField(
            model_name='solicitudnovedad',
            name='tarea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='novedades', to='tienda.solicitudtarea'),
        ),
    ]
