# Generated by Django 5.2.14 on 2026-05-31 02:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0011_cliente_proyecto_cliente_solicitud_cliente_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='nombre_comercial',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='cliente',
            name='preferencia_contacto',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='cliente',
            name='sector',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='cliente',
            name='sitio_web',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='estado_facturacion',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('facturado', 'Facturado'), ('pagado', 'Pagado'), ('anulado', 'Anulado')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='fecha_factura',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='numero_factura',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='valor_facturado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='solicitudnovedad',
            name='visible_para_cliente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solicitudrespuesta',
            name='visible_para_cliente',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='ClienteUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('puede_ver_proyectos', models.BooleanField(default=True)),
                ('puede_ver_solicitudes', models.BooleanField(default=True)),
                ('puede_ver_facturacion', models.BooleanField(default=False)),
                ('puede_descargar_archivos', models.BooleanField(default=True)),
                ('recibe_notificaciones', models.BooleanField(default=True)),
                ('fecha_ultimo_acceso', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_portal', to='tienda.cliente')),
                ('contacto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_portal', to='tienda.clientecontacto')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario de portal cliente',
                'verbose_name_plural': 'Usuarios de portal cliente',
                'ordering': ['cliente', 'user__email', 'user__username'],
            },
        ),
        migrations.CreateModel(
            name='NotificacionCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=160)),
                ('mensaje', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('sistema', 'Sistema'), ('pedido', 'Pedido'), ('proyecto', 'Proyecto'), ('facturacion', 'Facturacion'), ('documento', 'Documento'), ('novedad', 'Novedad')], default='sistema', max_length=30)),
                ('leida', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('url_destino', models.CharField(blank=True, max_length=255)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_cliente', to='tienda.cliente')),
                ('cliente_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='tienda.clienteusuario')),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones_cliente', to='tienda.proyecto')),
                ('solicitud', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_cliente', to='tienda.solicitud')),
            ],
            options={
                'verbose_name': 'Notificacion de cliente',
                'verbose_name_plural': 'Notificaciones de cliente',
                'ordering': ['-fecha_creacion', '-id'],
            },
        ),
    ]
