# Generated by Django 5.2.14 on 2026-05-31 03:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0012_cliente_nombre_comercial_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=30, unique=True)),
                ('titulo', models.CharField(max_length=180)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_emision', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('enviada', 'Enviada'), ('vista', 'Vista'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('vencida', 'Vencida'), ('convertida', 'Convertida'), ('anulada', 'Anulada')], default='borrador', max_length=30)),
                ('moneda', models.CharField(choices=[('COP', 'COP')], default='COP', max_length=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('descuento_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('impuesto_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('observaciones_cliente', models.TextField(blank=True)),
                ('condiciones_comerciales', models.TextField(blank=True)),
                ('tiempo_entrega', models.CharField(blank=True, max_length=160)),
                ('forma_pago', models.CharField(blank=True, max_length=160)),
                ('garantia', models.CharField(blank=True, max_length=160)),
                ('validez_dias', models.PositiveIntegerField(default=15)),
                ('enviada_a_email', models.EmailField(blank=True, max_length=254)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('actualizada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones_actualizadas', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones', to='tienda.cliente')),
                ('contacto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones', to='tienda.clientecontacto')),
                ('creada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones_creadas', to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones', to='tienda.proyecto')),
                ('solicitud', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones', to='tienda.solicitud')),
            ],
            options={
                'verbose_name': 'Cotizacion',
                'verbose_name_plural': 'Cotizaciones',
                'ordering': ['-fecha_creacion', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CotizacionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=240)),
                ('detalle', models.TextField(blank=True)),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('unidad', models.CharField(default='und', max_length=40)),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('descuento_porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('descuento_valor', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('impuesto_porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('descuento_calculado', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('impuesto_calculado', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tienda.cotizacion')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizacion_items', to='tienda.producto')),
            ],
            options={
                'verbose_name': 'Item de cotizacion',
                'verbose_name_plural': 'Items de cotizacion',
                'ordering': ['orden', 'id'],
            },
        ),
    ]
