# Generated by Django 5.2.14 on 2026-06-01 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0013_cotizacion_cotizacionitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cotizacion',
            options={'ordering': ['-fecha_creacion', '-id'], 'verbose_name': 'Cotización', 'verbose_name_plural': 'Cotizaciones'},
        ),
        migrations.AlterModelOptions(
            name='cotizacionitem',
            options={'ordering': ['orden', 'id'], 'verbose_name': 'Ítem de cotización', 'verbose_name_plural': 'Ítems de cotización'},
        ),
        migrations.AlterModelOptions(
            name='notificacion',
            options={'ordering': ['-fecha_creacion', '-id'], 'verbose_name': 'Notificación', 'verbose_name_plural': 'Notificaciones'},
        ),
        migrations.AlterModelOptions(
            name='notificacioncliente',
            options={'ordering': ['-fecha_creacion', '-id'], 'verbose_name': 'Notificación de cliente', 'verbose_name_plural': 'Notificaciones de cliente'},
        ),
        migrations.AlterModelOptions(
            name='solicitudasignacion',
            options={'ordering': ['-activa', 'fecha_asignacion'], 'verbose_name': 'Asignación de solicitud', 'verbose_name_plural': 'Asignaciones de solicitud'},
        ),
        migrations.AlterModelOptions(
            name='solicitudtarea',
            options={'ordering': ['solicitud', 'orden', 'fecha_limite', 'id'], 'verbose_name': 'Tarea de producción', 'verbose_name_plural': 'Tareas de producción'},
        ),
        migrations.AlterField(
            model_name='empleadoperfil',
            name='area',
            field=models.CharField(choices=[('produccion', 'Producción'), ('diseno', 'Diseño'), ('corte', 'Corte'), ('impresion', 'Impresión'), ('calidad', 'Calidad'), ('despacho', 'Despacho'), ('admin', 'Admin'), ('apoyo', 'Apoyo')], default='produccion', max_length=30),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('asignacion', 'Asignación'), ('desasignacion', 'Desasignación'), ('estado', 'Cambio de estado'), ('novedad', 'Novedad'), ('terminado', 'Terminado'), ('tarea', 'Tarea'), ('proyecto', 'Proyecto'), ('sistema', 'Sistema')], default='sistema', max_length=30),
        ),
        migrations.AlterField(
            model_name='notificacioncliente',
            name='tipo',
            field=models.CharField(choices=[('sistema', 'Sistema'), ('pedido', 'Pedido'), ('proyecto', 'Proyecto'), ('facturacion', 'Facturación'), ('documento', 'Documento'), ('novedad', 'Novedad')], default='sistema', max_length=30),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('pendiente', 'Pendiente'), ('en_planeacion', 'En planeación'), ('en_produccion', 'En producción'), ('pausado', 'Pausado'), ('terminado', 'Terminado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='borrador', max_length=30),
        ),
        migrations.AlterField(
            model_name='solicitudnovedad',
            name='tipo',
            field=models.CharField(choices=[('comentario', 'Comentario'), ('cambio_estado', 'Cambio de estado'), ('asignacion', 'Asignación'), ('desasignacion', 'Desasignación'), ('evidencia', 'Evidencia'), ('sistema', 'Sistema'), ('alerta', 'Alerta'), ('tarea_creada', 'Tarea creada'), ('tarea_asignada', 'Tarea asignada'), ('tarea_estado', 'Estado de tarea'), ('tarea_evidencia', 'Evidencia de tarea'), ('tarea_comentario', 'Comentario de tarea'), ('tarea_finalizada', 'Tarea finalizada')], default='comentario', max_length=30),
        ),
        migrations.AlterField(
            model_name='solicitudtarea',
            name='area',
            field=models.CharField(choices=[('diseno', 'Diseño'), ('preprensa', 'Preprensa'), ('impresion', 'Impresión'), ('laminado', 'Laminado'), ('corte', 'Corte'), ('ensamble', 'Ensamble'), ('calidad', 'Calidad'), ('instalacion', 'Instalación'), ('despacho', 'Despacho'), ('apoyo', 'Apoyo')], default='apoyo', max_length=30),
        ),
    ]
