# Generated by Django 5.2.14 on 2026-06-01 06:14

import django.db.models.deletion
from django.db import migrations, models


def backfill_contactos_portal(apps, schema_editor):
    ClienteContacto = apps.get_model("tienda", "ClienteContacto")
    Proyecto = apps.get_model("tienda", "Proyecto")
    Solicitud = apps.get_model("tienda", "Solicitud")

    contactos_por_cliente = {}
    contactos = ClienteContacto.objects.filter(activo=True).order_by("cliente_id", "-es_principal", "nombre")
    for contacto in contactos:
        contactos_por_cliente.setdefault(contacto.cliente_id, contacto.id)

    for proyecto in Proyecto.objects.filter(contacto__isnull=True, cliente__isnull=False):
        contacto_id = contactos_por_cliente.get(proyecto.cliente_id)
        if contacto_id:
            proyecto.contacto_id = contacto_id
            proyecto.save(update_fields=["contacto"])

    for solicitud in Solicitud.objects.filter(contacto__isnull=True).select_related("proyecto"):
        contacto_id = contactos_por_cliente.get(solicitud.cliente_id)
        if not contacto_id and solicitud.proyecto_id:
            contacto_id = solicitud.proyecto.contacto_id
        if contacto_id:
            solicitud.contacto_id = contacto_id
            solicitud.save(update_fields=["contacto"])


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0014_alter_cotizacion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienteusuario',
            name='puede_ver_toda_la_cuenta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='contacto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos', to='tienda.clientecontacto'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='contacto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes', to='tienda.clientecontacto'),
        ),
        migrations.RunPython(backfill_contactos_portal, migrations.RunPython.noop),
    ]
