# Generated by Django 5.2.14 on 2026-06-03 13:57

import django.db.models.deletion
from django.db import migrations, models


def backfill_proyecto(apps, schema_editor):
    SolicitudTarea = apps.get_model("tienda", "SolicitudTarea")
    SolicitudNovedad = apps.get_model("tienda", "SolicitudNovedad")

    tareas = SolicitudTarea.objects.filter(proyecto__isnull=True, solicitud__proyecto__isnull=False)
    for tarea in tareas.iterator():
        tarea.proyecto_id = tarea.solicitud.proyecto_id
        tarea.save(update_fields=["proyecto"])

    novedades = SolicitudNovedad.objects.filter(proyecto__isnull=True, solicitud__proyecto__isnull=False)
    for novedad in novedades.iterator():
        novedad.proyecto_id = novedad.solicitud.proyecto_id
        novedad.save(update_fields=["proyecto"])


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0015_clienteusuario_puede_ver_toda_la_cuenta_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitudtarea',
            options={'ordering': ['proyecto', 'solicitud', 'orden', 'fecha_limite', 'id'], 'verbose_name': 'Tarea de producción', 'verbose_name_plural': 'Tareas de producción'},
        ),
        migrations.AddField(
            model_name='solicitudnovedad',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='novedades', to='tienda.proyecto'),
        ),
        migrations.AddField(
            model_name='solicitudtarea',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas', to='tienda.proyecto'),
        ),
        migrations.AlterField(
            model_name='solicitudnovedad',
            name='solicitud',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='novedades', to='tienda.solicitud'),
        ),
        migrations.AlterField(
            model_name='solicitudtarea',
            name='solicitud',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='tienda.solicitud'),
        ),
        migrations.RunPython(backfill_proyecto, migrations.RunPython.noop),
    ]
