# Generated by Django 5.2.14 on 2026-06-06 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0016_alter_solicitudtarea_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen_principal',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
        migrations.AlterField(
            model_name='productoimagen',
            name='imagen',
            field=models.ImageField(upload_to='productos/galeria/'),
        ),
    ]
