# Generated by Django 5.2.17 on 2026-10-06 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0017_alter_producto_imagen_principal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientePuntoVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=160)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('ciudad', models.CharField(blank=True, max_length=120)),
                ('contacto', models.CharField(blank=True, max_length=160)),
                ('telefono', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('observaciones', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntos_venta', to='tienda.cliente')),
            ],
            options={
                'verbose_name': 'Punto de venta',
                'verbose_name_plural': 'Puntos de venta',
                'ordering': ['-activo', 'nombre'],
                'constraints': [models.UniqueConstraint(fields=('cliente', 'nombre'), name='unico_punto_venta_por_cliente_nombre')],
            },
        ),
    ]
