# Generated by Django 5.2.18 on 2026-10-08 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0020_alegra_reconciliation'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlegraContactStaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=120)),
                ('external_uuid', models.CharField(blank=True, max_length=160)),
                ('name', models.CharField(max_length=180)),
                ('identification', models.CharField(blank=True, max_length=80)),
                ('identification_type', models.CharField(blank=True, max_length=40)),
                ('verification_digit', models.CharField(blank=True, max_length=4)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_primary', models.CharField(blank=True, max_length=40)),
                ('phone_secondary', models.CharField(blank=True, max_length=40)),
                ('mobile', models.CharField(blank=True, max_length=40)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('department', models.CharField(blank=True, max_length=120)),
                ('country', models.CharField(blank=True, max_length=80)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('external_status', models.CharField(blank=True, max_length=30)),
                ('external_types', models.JSONField(blank=True, default=list)),
                ('classification', models.CharField(choices=[('linked', 'Vinculado'), ('probable', 'Coincidencia probable'), ('new', 'Nuevo'), ('conflict', 'Conflicto'), ('incomplete', 'Incompleto'), ('ignored', 'Ignorado')], default='incomplete', max_length=20)),
                ('classification_reason', models.CharField(blank=True, max_length=500)),
                ('classification_locked', models.BooleanField(default=False)),
                ('technical_data', models.JSONField(blank=True, default=dict)),
                ('error_detail', models.CharField(blank=True, max_length=500)),
                ('fetched_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contacto Alegra en revisión',
                'verbose_name_plural': 'Contactos Alegra en revisión',
                'ordering': ['-fetched_at', 'name'],
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='celular',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='cliente',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='cliente',
            name='departamento',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='cliente',
            name='digito_verificacion',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='cliente',
            name='pais',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefono_secundario',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='clientepuntoventa',
            name='codigo_interno',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='clientepuntoventa',
            name='departamento',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='clientepuntoventa',
            name='es_principal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='clientepuntoventa',
            constraint=models.UniqueConstraint(condition=models.Q(('activo', True), ('es_principal', True)), fields=('cliente',), name='unico_punto_principal_activo_por_cliente'),
        ),
        migrations.AddField(
            model_name='alegracontactstaging',
            name='imported_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alegra_staging_imports', to='tienda.cliente'),
        ),
        migrations.AddField(
            model_name='alegracontactstaging',
            name='matched_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alegra_staging_matches', to='tienda.cliente'),
        ),
        migrations.AddField(
            model_name='alegracontactstaging',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alegra_contacts', to='tienda.externalsystem'),
        ),
        migrations.AddIndex(
            model_name='alegracontactstaging',
            index=models.Index(fields=['classification', 'fetched_at'], name='alegra_contact_class_idx'),
        ),
        migrations.AddIndex(
            model_name='alegracontactstaging',
            index=models.Index(fields=['identification'], name='alegra_contact_id_idx'),
        ),
        migrations.AddConstraint(
            model_name='alegracontactstaging',
            constraint=models.UniqueConstraint(fields=('system', 'external_id'), name='unique_alegra_staging_contact'),
        ),
    ]
