# Generated by Django 5.2.18 on 2026-10-08 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0021_alegracontactstaging_cliente_celular_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='punto_venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones', to='tienda.clientepuntoventa'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='puntos_venta',
            field=models.ManyToManyField(blank=True, related_name='proyectos', to='tienda.clientepuntoventa'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='punto_venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes', to='tienda.clientepuntoventa'),
        ),
    ]
