# Generated by Django 5.2.18 on 2026-10-08 03:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0022_cotizacion_punto_venta_proyecto_puntos_venta_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlegraInvoiceStaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=120)),
                ('number', models.CharField(blank=True, max_length=120)),
                ('prefix', models.CharField(blank=True, max_length=40)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('client_external_id', models.CharField(blank=True, max_length=120)),
                ('client_name', models.CharField(blank=True, max_length=240)),
                ('client_identification', models.CharField(blank=True, max_length=100)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('tax', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('currency', models.CharField(blank=True, max_length=12)),
                ('external_status', models.CharField(choices=[('active', 'Activa'), ('void', 'Anulada'), ('draft', 'Borrador'), ('unknown', 'Desconocida')], default='unknown', max_length=30)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('payment_status', models.CharField(blank=True, max_length=40)),
                ('reference', models.CharField(blank=True, max_length=240)),
                ('original_data', models.JSONField(blank=True, default=dict)),
                ('data_hash', models.CharField(blank=True, max_length=64)),
                ('reconciliation_status', models.CharField(choices=[('unreviewed', 'Sin conciliar'), ('matched', 'Conciliada'), ('conflict', 'Conflicto'), ('ignored', 'Ignorada')], default='unreviewed', max_length=20)),
                ('fetched_at', models.DateTimeField()),
                ('first_synced_at', models.DateTimeField(auto_now_add=True)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('error_detail', models.CharField(blank=True, max_length=500)),
                ('matched_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alegra_invoice_staging', to='tienda.cliente')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alegra_invoices', to='tienda.externalsystem')),
            ],
            options={
                'verbose_name': 'Factura Alegra en staging',
                'verbose_name_plural': 'Facturas Alegra en staging',
                'ordering': ['-issue_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=30, unique=True)),
                ('fecha_venta', models.DateField(default=django.utils.timezone.localdate)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('confirmada', 'Confirmada'), ('en_proceso', 'En proceso'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='borrador', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('descuento_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('impuesto_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('observaciones', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('motivo_cancelacion', models.CharField(blank=True, max_length=500)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_actualizadas', to=settings.AUTH_USER_MODEL)),
                ('cancelado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_canceladas', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='tienda.cliente')),
                ('cotizacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to='tienda.cotizacion')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_creadas', to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to='tienda.proyecto')),
                ('punto_venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to='tienda.clientepuntoventa')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_responsables', to=settings.AUTH_USER_MODEL)),
                ('solicitud', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to='tienda.solicitud')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['-fecha_venta', '-id'],
            },
        ),
        migrations.CreateModel(
            name='VentaFacturaAlegra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidencia', models.CharField(max_length=500)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('confirmado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conciliaciones_venta_factura', to=settings.AUTH_USER_MODEL)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas_betta', to='tienda.alegrainvoicestaging')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas_alegra', to='tienda.venta')),
            ],
        ),
        migrations.CreateModel(
            name='VentaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=240)),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('unidad', models.CharField(default='und', max_length=40)),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('impuesto', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='venta_items', to='tienda.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tienda.venta')),
            ],
            options={
                'verbose_name': 'Ítem de venta',
                'verbose_name_plural': 'Ítems de venta',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='alegrainvoicestaging',
            index=models.Index(fields=['number', 'issue_date'], name='alegra_inv_num_date_idx'),
        ),
        migrations.AddIndex(
            model_name='alegrainvoicestaging',
            index=models.Index(fields=['reconciliation_status'], name='alegra_inv_recon_idx'),
        ),
        migrations.AddConstraint(
            model_name='alegrainvoicestaging',
            constraint=models.UniqueConstraint(fields=('system', 'external_id'), name='unique_alegra_invoice_staging'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['fecha_venta', 'estado'], name='venta_fecha_estado_idx'),
        ),
        migrations.AddConstraint(
            model_name='ventafacturaalegra',
            constraint=models.UniqueConstraint(fields=('venta', 'factura'), name='unique_venta_alegra_invoice_link'),
        ),
    ]
