# Generated by Django 5.2.18 on 2026-10-08 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0023_alegrainvoicestaging_venta_ventafacturaalegra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alegrainvoicestaging',
            name='line_items',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
