# Generated by Django 5.2.18 on 2026-10-08 03:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0024_alegrainvoicestaging_line_items'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='alegrainvoicestaging',
            name='external_status',
            field=models.CharField(choices=[('active', 'Activa'), ('open', 'Abierta'), ('closed', 'Cerrada'), ('void', 'Anulada'), ('draft', 'Borrador'), ('unknown', 'Desconocida')], default='unknown', max_length=30),
        ),
        migrations.CreateModel(
            name='CarteraGestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_gestion', models.DateTimeField(default=django.utils.timezone.now)),
                ('tipo', models.CharField(choices=[('llamada', 'Llamada'), ('correo', 'Correo'), ('whatsapp', 'WhatsApp'), ('reunion', 'Reunión'), ('otro', 'Otro')], max_length=20)),
                ('resultado', models.CharField(max_length=240)),
                ('observaciones', models.TextField(blank=True)),
                ('proxima_accion', models.CharField(blank=True, max_length=240)),
                ('fecha_seguimiento', models.DateField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gestiones_cartera', to='tienda.cliente')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gestiones_cartera_creadas', to=settings.AUTH_USER_MODEL)),
                ('factura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gestiones_cartera', to='tienda.alegrainvoicestaging')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gestiones_cartera', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_gestion', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CompromisoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_comprometida', models.DateField()),
                ('valor_comprometido', models.DecimalField(decimal_places=2, max_digits=14)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('cumplido', 'Cumplido'), ('incumplido', 'Incumplido'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compromisos_pago', to='tienda.cliente')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compromisos_pago_creados', to=settings.AUTH_USER_MODEL)),
                ('factura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compromisos_pago', to='tienda.alegrainvoicestaging')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compromisos_pago', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AlegraPaymentStaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=120)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('client_external_id', models.CharField(blank=True, max_length=120)),
                ('client_name', models.CharField(blank=True, max_length=240)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('currency', models.CharField(blank=True, max_length=12)),
                ('payment_method', models.CharField(blank=True, max_length=40)),
                ('external_status', models.CharField(blank=True, max_length=40)),
                ('invoice_external_ids', models.JSONField(blank=True, default=list)),
                ('reference', models.CharField(blank=True, max_length=240)),
                ('original_data', models.JSONField(blank=True, default=dict)),
                ('data_hash', models.CharField(blank=True, max_length=64)),
                ('reconciliation_status', models.CharField(choices=[('unreviewed', 'Sin conciliar'), ('matched', 'Conciliado'), ('conflict', 'Conflicto'), ('ignored', 'Ignorado')], default='unreviewed', max_length=20)),
                ('fetched_at', models.DateTimeField()),
                ('first_synced_at', models.DateTimeField(auto_now_add=True)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('error_detail', models.CharField(blank=True, max_length=500)),
                ('matched_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alegra_payment_staging', to='tienda.cliente')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alegra_payments', to='tienda.externalsystem')),
            ],
            options={
                'verbose_name': 'Pago Alegra en staging',
                'verbose_name_plural': 'Pagos Alegra en staging',
                'ordering': ['-payment_date', '-id'],
                'indexes': [models.Index(fields=['payment_date'], name='alegra_pay_date_idx'), models.Index(fields=['reconciliation_status'], name='alegra_pay_recon_idx')],
                'constraints': [models.UniqueConstraint(fields=('system', 'external_id'), name='unique_alegra_payment_staging')],
            },
        ),
        migrations.CreateModel(
            name='CarteraResponsable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('asignado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_cartera_creadas', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_cartera', to='tienda.cliente')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_cartera', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('cliente',), name='unique_active_cartera_responsible')],
            },
        ),
    ]
