# Generated by Django 5.2.18 on 2026-10-08 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('tienda', '0025_alter_alegrainvoicestaging_external_status_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='externalobjectmap',
            constraint=models.UniqueConstraint(condition=models.Q(('content_type__isnull', False), ('object_id__isnull', False), ('status', 'active')), fields=('system', 'resource_type', 'content_type', 'object_id'), name='unique_active_external_local_object'),
        ),
    ]
