# Generated by Django 5.2.18 on 2026-10-08 05:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0026_p1a_integridad_referencial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='estado',
            field=models.CharField(choices=[('abierta', 'Abierta'), ('resuelta', 'Resuelta')], default='abierta', max_length=20),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='event_key',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='resuelta_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='notificacion',
            constraint=models.UniqueConstraint(condition=models.Q(('event_key', ''), _negated=True), fields=('usuario_destino', 'event_key'), name='unique_notification_event_per_user'),
        ),
    ]
