# Generated by Django 5.2.18 on 2026-10-08 05:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0027_notificacion_estado_notificacion_event_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='notificacion',
            name='unique_notification_event_per_user',
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='event_key',
            field=models.CharField(blank=True, default=None, max_length=180, null=True),
        ),
        migrations.AddConstraint(
            model_name='notificacion',
            constraint=models.UniqueConstraint(fields=('usuario_destino', 'event_key'), name='unique_notification_event_per_user'),
        ),
    ]
