# Generated by Django 5.2.18 on 2026-10-08 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0028_remove_notificacion_unique_notification_event_per_user_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cliente',
            name='cliente_email_unico_si_existe',
        ),
    ]
