# Generated by Django 5.2.18 on 2026-10-08 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0029_remove_cliente_cliente_email_unico_si_existe'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlegraWriteOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(default='contacts', max_length=80)),
                ('operation', models.CharField(choices=[('create', 'Crear contacto'), ('update', 'Actualizar contacto')], max_length=20)),
                ('external_id', models.CharField(blank=True, max_length=120)),
                ('state', models.CharField(choices=[('pending', 'Pendiente'), ('sent', 'Enviada'), ('synced', 'Sincronizada'), ('failed', 'Fallida'), ('conflict', 'Conflicto'), ('needs_reconciliation', 'Requiere conciliación')], default='pending', max_length=32)),
                ('idempotency_key', models.CharField(max_length=64, unique=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=40)),
                ('error_message', models.CharField(blank=True, max_length=500)),
                ('reconciliation_reason', models.CharField(blank=True, max_length=500)),
                ('result_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alegra_write_operations', to='tienda.cliente')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='write_operations', to='tienda.externalsystem')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['system', 'client', 'state'], name='alegra_write_client_idx'), models.Index(fields=['resource_type', 'external_id'], name='alegra_write_ext_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('operation__in', ['create', 'update'])), name='alegra_write_operation_valid')],
            },
        ),
    ]
