# Generated by Django 5.2.18 on 2026-10-08 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0031_cliente_datos_colombia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='tienda.categoria'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo_calculo',
            field=models.CharField(blank=True, choices=[('manual', 'Manual / requiere revisión'), ('area_m2', 'Área m²'), ('unidad', 'Por unidad')], default='', max_length=20),
        ),
    ]
