# Generated by Django 5.2.18 on 2026-10-08 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0032_alter_producto_categoria_alter_producto_tipo_calculo'),
    ]

    operations = [
        migrations.CreateModel(
            name='UNSPSCCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8)),
                ('description', models.CharField(max_length=255)),
                ('level', models.CharField(choices=[('segment', 'Segmento'), ('family', 'Familia'), ('class', 'Clase'), ('product', 'Producto')], max_length=12)),
                ('catalog_version', models.CharField(max_length=40)),
                ('active', models.BooleanField(default=True)),
                ('source', models.CharField(blank=True, max_length=255)),
                ('imported_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='tienda.unspsccode')),
            ],
            options={
                'verbose_name': 'Código UNSPSC',
                'verbose_name_plural': 'Códigos UNSPSC',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='unspsc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='tienda.unspsccode'),
        ),
        migrations.AddIndex(
            model_name='unspsccode',
            index=models.Index(fields=['code'], name='unspsc_code_idx'),
        ),
        migrations.AddIndex(
            model_name='unspsccode',
            index=models.Index(fields=['catalog_version', 'active'], name='unspsc_version_active_idx'),
        ),
        migrations.AddIndex(
            model_name='unspsccode',
            index=models.Index(fields=['description'], name='unspsc_description_idx'),
        ),
        migrations.AddConstraint(
            model_name='unspsccode',
            constraint=models.UniqueConstraint(fields=('catalog_version', 'code'), name='unspsc_version_code_unique'),
        ),
    ]
