# Generated by Django 5.2.18 on 2026-10-08 21:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0033_unspsccode_producto_unspsc_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UNSPSCImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=255, upload_to='private/unspsc/')),
                ('catalog_version', models.CharField(max_length=40)),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pendiente de validación'), ('ready', 'Vista previa lista'), ('apply_requested', 'Aplicación solicitada'), ('processing', 'Procesando'), ('completed', 'Completada'), ('failed', 'Fallida')], default='pending', max_length=24)),
                ('source_rows', models.PositiveIntegerField(default=0)),
                ('unique_codes', models.PositiveIntegerField(default=0)),
                ('invalid_rows', models.PositiveIntegerField(default=0)),
                ('duplicate_rows', models.PositiveIntegerField(default=0)),
                ('preview', models.JSONField(blank=True, default=dict)),
                ('error_message', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Importación de catálogo UNSPSC',
                'verbose_name_plural': 'Importaciones de catálogo UNSPSC',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='unspsc_job_status_idx')],
            },
        ),
    ]
