# Generated by Django 5.2

from django.db import migrations, models

import tienda.storage


class Migration(migrations.Migration):

    dependencies = [
        ("tienda", "0034_unspscimportjob"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unspscimportjob",
            name="file",
            field=models.FileField(
                max_length=255,
                storage=tienda.storage.PrivateMediaStorage(),
                upload_to="private/unspsc/",
            ),
        ),
    ]
