# Generated by Django 5.2

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tienda", "0035_private_unspsc_storage"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlegraProductWriteOperation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("operation", models.CharField(choices=[("create", "Crear producto"), ("update", "Actualizar producto")], max_length=20)),
                ("external_id", models.CharField(blank=True, max_length=120)),
                ("state", models.CharField(choices=[("pending", "Pendiente"), ("sent", "Enviada"), ("synced", "Sincronizada"), ("failed", "Fallida"), ("blocked", "Requiere revisión"), ("needs_reconciliation", "Requiere conciliación")], default="pending", max_length=32)),
                ("idempotency_key", models.CharField(max_length=64, unique=True)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("last_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("error_code", models.CharField(blank=True, max_length=40)),
                ("error_message", models.CharField(blank=True, max_length=500)),
                ("result_metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="alegra_write_operations", to="tienda.producto")),
                ("system", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="product_write_operations", to="tienda.externalsystem")),
            ],
            options={
                "ordering": ["created_at", "id"],
                "indexes": [
                    models.Index(fields=["system", "product", "state"], name="alegra_prod_write_idx"),
                    models.Index(fields=["external_id", "state"], name="alegra_prod_ext_idx"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="alegraproductwriteoperation",
            constraint=models.CheckConstraint(condition=models.Q(("operation__in", ["create", "update"])), name="alegra_prod_write_op_valid"),
        ),
    ]
